- name: error handling
  connection: local
  hosts: local
  become: yes
  tasks:
  - name: check user exist or noquota
    ansible.builtin.command: id roboshop
    register: user_outut
    ignore_errors: true
  
  - name: print the output
    ansible.builtin.debug:
     msg: "{{user_output}}"

  - name: create user if user not exist
    ansible.builtin.command: useradd roboshop
    when: user_output.rc != 0