- name: functions
  hosts: local
  connection: local
  become: yes

  vars:
    technologies: Devops,ansible,aws  #string
    
    tags:
     Application: payment
     env: dev
  
  tasks:
  - name: variables without defining
    ansible.builtin.debug:
     msg: "{{ user | default('ramesh') }}"

  - name: covert string to list
    ansible.builtin.debug:
     msg: "{{ technologies | split(',') }}"

  - name: covert tags to list
    ansible.builtin.debug:
     msg: "lists :{{ tags | dict2items }}"