- name: functions
  hosts: local
  connection: local
  become: yes

  vars:
    technologies: Devops,ansible,aws  #string
    
    tags:
     Application: payment
     env: dev

    upper: AKASH
    lower: pavan

    ip_address: 55.0.0.0

    listTags:
    - key: Application
      value: payment
    - key: Environment
      value: dev
  
  tasks:
  - name: variables without defining
    ansible.builtin.debug:
     msg: "{{ user | default('ramesh') }}"

  - name: covert string to list
    ansible.builtin.debug:
     msg: "{{ technologies | split(',') }}"

  - name: covert tags to list
    ansible.builtin.debug:
     msg: "lists :{{ tags | dict2items }}"

  - name: convert list into map
    ansible.builtin.debug:
      msg: "tag map: {{ listTags | items2dict }}"

  - name: covert upper to lowerrrr
    ansible.builtin.debug:
      msg: "lowercase: {{ upper | lower }}"

  - name: covert lower to upperrrr
    ansible.builtin.debug:
      msg: "uppercase: {{ lower | upper }}"

  - name: to check if ip address is valid or not
    ansible.builtin.debug:
      msg: "ip address: {{ ip_address | ansible.utils.ipv4 }}"
    
  - name: grep for root
    # ansible.builtin.command: cat /etc/passwd | grep root
    ansible.builtin.shell: cat /etc/passwd | grep root
    register: output

  - name: print the output
    ansible.builtin.debug:
      msg: "{{ output }}"
