- name: installing packages
  connection: local
  hosts: local
  become: yes
  tasks:
  - name: print names
    ansible.builtin.package:
      name: "{{item}}"
      state: latest
    loop:
    - nginx
    - mysql
    - zip