- name: variable preferences
  hosts: local
  connection: local
  vars:
  name: akash
  vars_files:
    course.yaml
  vars_prompt:
    name: username
    what is username: what is username?
    private: true
  tasks:
  - name: printing variables based on preferences
    vars:
      name: pavan
    ansible.builtin.debug:
      msg: "name:{{name}}"
    